packages:
  - "actions/*"
  - "packages/*"
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@kungfu-tech/kfd'
  - '@kungfu-tech/buildchain@3.0.9-alpha.11'
