import assert from "node:assert/strict";
import test from "node:test";
import { verifyReleaseFinalization } from "../packages/core/release/next-development/finalization.js";
import { assertReviewPull, assertReviewRun } from "../packages/core/release/next-development/review-policy.js";

function fixture() {
  const baseSha = "a".repeat(40), headSha = "b".repeat(40), stateSha = "c".repeat(40);
  const repository = "kungfu-systems/buildchain";
  const branch = `chore/v4-product-pr/release-v4-v4.0/${stateSha.slice(0, 12)}-${baseSha.slice(0, 12)}-${headSha.slice(0, 12)}`;
  const run = { id: 123, repository: { full_name: repository }, head_sha: headSha, head_branch: branch,
    path: ".github/workflows/self-build-verify.yml", name: "Verify", event: "pull_request", status: "completed", conclusion: "success" };
  const pull = { number: 12, state: "open", draft: false, user: { login: "dongkeren" },
    head: { sha: headSha, ref: branch, repo: { full_name: repository } },
    base: { sha: baseSha, ref: "release/v4/v4.0", repo: { full_name: repository } } };
  const data = new Map([
    [`repos/${repository}/git/ref/heads/buildchain/v4-product-state/${baseSha}-4-0-6`, { object: { sha: stateSha } }],
    [`repos/${repository}/git/ref/tags/v4.0.6`, { object: { type: "commit", sha: baseSha } }],
    [`repos/${repository}/git/commits/${baseSha}`, { committer: { date: "2026-09-08T00:00:00Z" } }],
  ]);
  const objects = new Map([
    [`show -s --format=%P ${headSha}`, `${baseSha} ${stateSha}`],
    [`show -s --format=%P ${stateSha}`, baseSha],
    [`show ${headSha}:package.json`, '{"version":"4.0.6"}'],
    [`show ${baseSha}:package.json`, '{"version":"4.0.6-alpha.0"}'],
    [`rev-parse ${stateSha}^{tree}`, "d".repeat(40)],
    [`rev-parse ${headSha}^{tree}`, "d".repeat(40)],
  ]);
  let regenerations = 0;
  return { data, objects, run, pull, baseSha, headSha, stateSha, repository, branch,
    options: { repository, run, pull, baseSha, client: { json: (key) => data.get(key) },
      git: (...args) => objects.get(args.join(" ")),
      regenerate: ({ version }) => { regenerations += 1; return { version }; } },
    count: () => regenerations,
  };
}

test("exact stable tag, protected parents and regenerated bytes qualify bounded finalization", () => {
  const f = fixture();
  assertReviewRun(f.run, { repository: f.repository, runId: 123, headSha: f.headSha });
  assertReviewPull(f.pull, f);
  const plan = verifyReleaseFinalization(f.options);
  assert.equal(plan.kind, "stable-finalization");
  assert.equal(plan.publicationSourceSha, f.baseSha);
  assert.equal(plan.publicationReceiptRoot, undefined);
  assert.equal(f.count(), 1);
});

test("wrong tag, extra parent, divergent state, changed version or unregenerable bytes reject finalization", () => {
  for (const change of [
    (f) => { f.data.get(`repos/${f.repository}/git/ref/tags/v4.0.6`).object.sha = f.headSha; },
    (f) => { f.objects.set(`show -s --format=%P ${f.headSha}`, `${f.baseSha} ${f.stateSha} ${f.headSha}`); },
    (f) => { f.objects.set(`rev-parse ${f.stateSha}^{tree}`, "wrong"); },
    (f) => { f.objects.set(`show ${f.headSha}:package.json`, '{"version":"4.0.7"}'); },
    (f) => { f.options.regenerate = () => { throw new Error("unregenerable source delta"); }; },
  ]) {
    const f = fixture(); change(f);
    assert.throws(() => verifyReleaseFinalization(f.options));
  }
});

test("stable finalization cannot review a fork or different protected release line", () => {
  const f = fixture();
  for (const change of [
    (pull) => { pull.base.ref = "release/v4/v4.1"; },
    (pull) => { pull.head.repo.full_name = "fork/buildchain"; },
    (pull) => { pull.head.sha = f.baseSha; },
  ]) {
    const pull = structuredClone(f.pull); change(pull);
    assert.throws(() => assertReviewPull(pull, f));
  }
});
