import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { projectRenamedMetrics } from "../scripts/source-metric-lineage.mjs";

test("metric inheritance follows an observed Git rename, never a copy or unrelated target", t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "buildchain-metric-lineage-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  git("init", "--quiet");
  fs.writeFileSync(path.join(root, "source.mjs"), "export const uniqueSource = 1;\n");
  fs.writeFileSync(path.join(root, "retained.mjs"), "export const retainedSource = 2;\n");
  git("add", ".");
  git("-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "--quiet", "-m", "fixture");
  const revision = git("rev-parse", "HEAD").trim();
  const target = "nested/renamed module.mjs";
  fs.mkdirSync(path.join(root, "nested"));
  git("mv", "source.mjs", target);
  fs.copyFileSync(path.join(root, "retained.mjs"), path.join(root, "copied.mjs"));
  git("add", ".");
  const sourceMetric = { file: "source.mjs", sourceLines: 42 };
  const metrics = { "source.mjs": sourceMetric, "retained.mjs": { sourceLines: 7 } };
  const currentPaths = new Set([target, "retained.mjs", "copied.mjs"]);
  const result = projectRenamedMetrics({ root, revision, metrics, currentPaths });
  assert.deepEqual(result.renames, [{ source: "source.mjs", target, similarity: 100 }]);
  assert.deepEqual(result.metrics[target], { ...sourceMetric, file: target });
  assert.equal(result.metrics["copied.mjs"], undefined);
  assert.deepEqual(metrics["source.mjs"], sourceMetric);
  assert.equal(metrics[target], undefined);
  assert.deepEqual(projectRenamedMetrics({ root, revision, metrics, currentPaths: new Set() }).renames, []);
  const existing = { sourceLines: 3 };
  const priorTarget = projectRenamedMetrics({ root, revision, metrics: { ...metrics, [target]: existing }, currentPaths });
  assert.deepEqual(priorTarget.renames, []);
  assert.equal(priorTarget.metrics[target], existing);
});
