name: "Batch Pull Request"
author: "songzhouran"
description: "Batch Pull Request"
inputs:
  token:
    description: "Github token. E.g. secrets.GITHUB_TOKEN"
  branch:
    description: "Choices [auto/prebuild/postbuild/verify]"
    default: "1.0"
  repo:
    description: "repo"
    default: "broker"
  version:
    description: "version"
    default: "alpha"
  repo-includes:
    description: "repo includes. Use, separate"
    require: false
  repo-excludes:
    description: "repo excludes. Use, separate"
    require: false
  pull-request-title:
    description: "pullRequestTitle"
    require: false
runs:
  using: "node24"
  main: "dist/index.js"