import * as github from "@actions/github";
import { releaseCandidateRecoveryReceiptPath } from "./action-environment.js";
export function createProviderClients(inputs) {
  const {
    token,
    generatedStatusCheckToken,
    generatedPullRequestToken,
    generatedRefUpdateToken,
    tagUpdateToken,
  } = inputs;
  const octokit = github.getOctokit(token);
  const statusCheckOctokit =
    generatedStatusCheckToken === token
      ? octokit
      : github.getOctokit(generatedStatusCheckToken);
  const pullRequestOctokit =
    generatedPullRequestToken === token
      ? octokit
      : github.getOctokit(generatedPullRequestToken);
  const refUpdateOctokit =
    generatedRefUpdateToken === token
      ? octokit
      : github.getOctokit(generatedRefUpdateToken);
  const tagUpdateOctokit =
    tagUpdateToken === token ? octokit : github.getOctokit(tagUpdateToken);
  return {
    octokit,
    statusCheckOctokit,
    pullRequestOctokit,
    refUpdateOctokit,
    tagUpdateOctokit,
  };
}
export function createPromotionRequest(inputs, clients) {
  const {
    token,
    sha,
    targetRef,
    tagInput,
    tags,
    dryRun,
    requireGovernance,
    requireVersionState,
    verificationCommand,
    reconciliationWorkspace,
    requiredStatusCheck,
    generatedStatusCheckToken,
    generatedPullRequestToken,
    generatedRefUpdateToken,
    tagUpdateToken,
    branchProtectionBypassApps,
    allowRepository,
    publishTransaction,
    publishCommand,
    publishProvider,
    publishEvidencePath,
    transactionStatePath,
    publishSealedBundleRoot,
    publishSealedBundleManifest,
    publishRequiredArtifactsPath,
    publishRequiredArtifactsJson,
    publishMode,
    publishAuth,
    publishDistTag,
    publishPackageSetOrder,
    publishPackageMain,
    expectedPublicationVersion,
    requirePublicationQualification,
    publicationCapabilityJson,
    publicationGateAggregateJson,
    publicationQualificationReceiptJson,
    publicationUsedQualificationNoncesJson,
    requirePublishSourceLock,
    publishSourceRef,
    publishSourceSha,
    publishSourceLocked,
    releaseMaterialSha,
    publishToolingSha,
    publishTransactionOverride,
    publishRematerializeOnResume,
    releasePassport,
    releasePassportOutputDir,
    releasePassportProductName,
    releasePassportBuildSummaryPath,
    releasePassportPlatformManifestPaths,
    releasePassportImpactJson,
    releasePassportPromotionRoutingJson,
    releasePassportConsumerPolicyCertificationJson,
    releasePassportConsumerPolicyCertificationRoot,
    releasePassportRuntimeResumeEvidenceJson,
    releasePassportRuntimeResumeEvidenceCommand,
    releasePassportKfd1WitnessJsons,
    releasePassportKfd2ClaimJsons,
    releasePassportKfd3PrebuildWitnessJsons,
    releasePassportKfd3ArtifactWitnessJsons,
    releasePassportKfd3ArtifactVerifyCommand,
    releasePassportKfdAdopterManifestJson,
    releasePassportKfdSupportMatrixJson,
    releasePassportKfdProductGateJsons,
    releasePassportInvariantPassportJsons,
    releasePassportInvariantPassportCommand,
    releasePassportEvidenceJsons,
    releasePassportAttachmentCommand,
    releasePassportBuildchainSelfKfd,
    releasePassportGitHubArtifactAttestationPolicyJsons,
    githubRelease,
    releaseTailStatePath,
    githubReleaseArtifactPaths,
    promoteOnlyReleaseCandidate,
    releaseCandidatePassportPath,
    releaseCandidateBuildSummaryPath,
    releaseCandidateVersion,
    releaseCandidateFamilyEvidenceRequired,
    releaseCandidateFamilyEvidenceRoot,
    releaseCandidateFamilyInitiativeId,
    releaseCandidateFamilyAssignmentId,
  } = inputs;
  const {
    octokit,
    statusCheckOctokit,
    pullRequestOctokit,
    refUpdateOctokit,
    tagUpdateOctokit,
  } = clients;
  return {
    octokit,
    owner: github.context.repo.owner,
    repo: github.context.repo.repo,
    sha,
    targetRef,
    tags,
    dryRun,
    allowRepository,
    requireGovernance,
    requireVersionState,
    verificationCommand,
    reconciliationWorkspace,
    requiredStatusCheck,
    statusCheckOctokit,
    pullRequestOctokit,
    refUpdateOctokit,
    tagUpdateOctokit,
    branchProtectionBypassApps,
    publishTransaction,
    publishCommand,
    publishProvider,
    publishEvidencePath,
    transactionStatePath,
    expectedTransactionId: process.env.BUILDCHAIN_EXPECTED_TRANSACTION_ID,
    publishSealedBundleRoot,
    publishSealedBundleManifest,
    publishRequiredArtifactsJson,
    publishMode,
    publishAuth,
    publishDistTag,
    publishPackageSetOrder,
    publishPackageMain,
    publishRematerializeOnResume,
    expectedPublicationVersion,
    requirePublicationQualification,
    publicationCapabilityJson,
    publicationGateAggregateJson,
    publicationQualificationReceiptJson,
    publicationUsedQualificationNoncesJson,
    releaseMaterialSha,
    publishToolingSha,
    releasePassport,
    releasePassportOutputDir,
    releasePassportProductName,
    releasePassportBuildSummaryPath,
    releasePassportPlatformManifestPaths,
    releasePassportImpactJson,
    releasePassportPromotionRoutingJson,
    releasePassportConsumerPolicyCertificationJson,
    releasePassportConsumerPolicyCertificationRoot,
    releasePassportRuntimeResumeEvidenceJson,
    releasePassportRuntimeResumeEvidenceCommand,
    releasePassportKfd1WitnessJsons,
    releasePassportKfd2ClaimJsons,
    releasePassportKfd3PrebuildWitnessJsons,
    releasePassportKfd3ArtifactWitnessJsons,
    releasePassportKfd3ArtifactVerifyCommand,
    releasePassportKfdAdopterManifestJson,
    releasePassportKfdSupportMatrixJson,
    releasePassportKfdProductGateJsons,
    releasePassportInvariantPassportJsons,
    releasePassportInvariantPassportCommand,
    releasePassportEvidenceJsons,
    releasePassportAttachmentCommand,
    releasePassportBuildchainSelfKfd,
    releasePassportGitHubArtifactAttestationPolicyJsons,
    promoteOnlyReleaseCandidate,
    releaseCandidatePassportPath,
    releaseCandidateBuildSummaryPath,
    releaseCandidateVersion,
    releaseCandidateRecoveryReceiptPath,
    releaseCandidateFamilyEvidenceRequired,
    releaseCandidateFamilyEvidenceRoot,
    releaseCandidateFamilyInitiativeId,
    releaseCandidateFamilyAssignmentId,
    actor: github.context.actor,
    runId: String(github.context.runId || ""),
    publishTransactionOverride,
  };
}
