export function normalizePassportOptions(options) {
  const {
    cwd = process.cwd(),
    repository = "",
    tag = "",
    sourceSha = "",
    line = "",
    productName = "Buildchain",
    packageName = "@kungfu-tech/buildchain",
    packageVersion = "",
    productMechanismPath = "product-mechanism.json",
    artifactEvidencePath = "artifact-evidence.json",
    impactPath = "impact.json",
    agentIndexPath = "agent-index.json",
    checkReportPath = "check-report.json",
    publishEvidencePath = "",
    transactionStatePath = "",
    assets = [],
    packageSet = undefined,
    anchorManifest = undefined,
    versionMaterial = undefined,
    publishEvidence = undefined,
    trustedPublishing = undefined,
    transaction = undefined,
    buildSummary = undefined,
    buildFacts = [],
    platformArtifactManifests = [],
    distTagPromotionEvidence = undefined,
    release = {},
    publish = {},
    impact = undefined,
    workflow = {},
    kfd1 = undefined,
    kfd2Claims = [],
    kfd3 = undefined,
    kfdAdopter = undefined,
    kfdAdopterManifestEvidencePath = "",
    kfdAdopterGateEvidencePath = "",
    kfdSupport = undefined,
    kfdSupportEvidencePath = "",
    invariantPassports = undefined,
    releaseEvidence = [],
    v4ConsumerPolicyCertification:
      domainConsumerPolicyCertification = undefined,
    v4ConsumerPolicyCertificationRoot:
      domainConsumerPolicyCertificationRoot = "",
    domainRuntimeResumeEvidence = undefined,
    kfdAgentHubEvidence = undefined,
    kfdAgentHubEvidencePath = "",
    controllerReceipts = [],
    controllerReceiptReferences = [],
    githubArtifactAttestations = [],
    checkedAt = "",
  } = options;
  return {
    options,
    cwd,
    repository,
    tag,
    sourceSha,
    line,
    productName,
    packageName,
    packageVersion,
    productMechanismPath,
    artifactEvidencePath,
    impactPath,
    agentIndexPath,
    checkReportPath,
    publishEvidencePath,
    transactionStatePath,
    assets,
    packageSet,
    anchorManifest,
    versionMaterial,
    publishEvidence,
    trustedPublishing,
    transaction,
    buildSummary,
    buildFacts,
    platformArtifactManifests,
    distTagPromotionEvidence,
    release,
    publish,
    impact,
    workflow,
    kfd1,
    kfd2Claims,
    kfd3,
    kfdAdopter,
    kfdAdopterManifestEvidencePath,
    kfdAdopterGateEvidencePath,
    kfdSupport,
    kfdSupportEvidencePath,
    invariantPassports,
    releaseEvidence,
    domainConsumerPolicyCertification,
    domainConsumerPolicyCertificationRoot,
    domainRuntimeResumeEvidence,
    kfdAgentHubEvidence,
    kfdAgentHubEvidencePath,
    controllerReceipts,
    controllerReceiptReferences,
    githubArtifactAttestations,
    checkedAt,
  };
}
