export function normalizePassportCollectionOptions({
  cwd = process.cwd(),
  tag = "",
  repository = process.env.GITHUB_REPOSITORY || "",
  sourceSha = process.env.GITHUB_SHA || "",
  line = "",
  outputDir = ".buildchain/release-passport",
  assetsJson = "",
  assetsDir = "",
  releaseJson = "",
  productName = "Buildchain",
  packageName = "@kungfu-tech/buildchain",
  packageVersion = "",
  packageSetJson = "",
  publishEvidenceJson = "",
  trustedPublishingJson = "",
  transactionJson = "",
  anchorManifestJson = "",
  versionMaterialJson = "",
  impactJson = "",
  buildSummaryJson = "",
  buildFactsJsons = [],
  platformManifestJsons = [],
  distTagEvidenceJson = "",
  kfd1WitnessJsons = [],
  kfd2ClaimJsons = [],
  kfd3PrebuildWitnessJsons = [],
  kfd3ArtifactWitnessJsons = [],
  kfd3ArtifactVerifyCommand = "",
  kfdAdopterManifestJson = "",
  kfdSupportMatrixJson = "",
  kfdProductGateJsons = [],
  invariantPassportJsons = [],
  invariantPassportCommand = "",
  releaseEvidenceJsons = [],
  v4ConsumerPolicyCertificationJson: domainConsumerPolicyCertificationJson = "",
  v4ConsumerPolicyCertificationRoot: domainConsumerPolicyCertificationRoot = "",
  v4RuntimeResumeEvidenceJson: domainRuntimeResumeEvidenceJson = "",
  kfdAgentHubEvidenceJson = "",
  controllerReceiptReferences = [],
  githubArtifactAttestationPolicyJsons = [],
  basePassportJson = "",
  requireBaseKfd = false,
  releaseJsonExtra = "",
  publishJson = "",
  workflow = {},
  checkedAt = "",
} = {}) {
  return {
    cwd,
    tag,
    repository,
    sourceSha,
    line,
    outputDir,
    assetsJson,
    assetsDir,
    releaseJson,
    productName,
    packageName,
    packageVersion,
    packageSetJson,
    publishEvidenceJson,
    trustedPublishingJson,
    transactionJson,
    anchorManifestJson,
    versionMaterialJson,
    impactJson,
    buildSummaryJson,
    buildFactsJsons,
    platformManifestJsons,
    distTagEvidenceJson,
    kfd1WitnessJsons,
    kfd2ClaimJsons,
    kfd3PrebuildWitnessJsons,
    kfd3ArtifactWitnessJsons,
    kfd3ArtifactVerifyCommand,
    kfdAdopterManifestJson,
    kfdSupportMatrixJson,
    kfdProductGateJsons,
    invariantPassportJsons,
    invariantPassportCommand,
    releaseEvidenceJsons,
    domainConsumerPolicyCertificationJson,
    domainConsumerPolicyCertificationRoot,
    domainRuntimeResumeEvidenceJson,
    kfdAgentHubEvidenceJson,
    controllerReceiptReferences,
    githubArtifactAttestationPolicyJsons,
    basePassportJson,
    requireBaseKfd,
    releaseJsonExtra,
    publishJson,
    workflow,
    checkedAt,
  };
}
