name: Admin - Channel Bump Version
on:
  pull_request:
    types: [closed]
    branches:
      - major-gate
      - release/*/lts

jobs:
  bump:
    uses: ./.github/workflows/.bump-minor-version.yml
    secrets:
      GITHUB_PUSH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
