name: Buildchain OCI Compose Preview

on:
  workflow_call:

    inputs:
    secrets:
      BUILDCHAIN_PROMOTION_TOKEN:
        required: true

permissions:
  contents: read

concurrency:
  group: buildchain-oci-compose-preview-${{ github.repository }}
  cancel-in-progress: false

jobs:
  promote:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
      - name: Check out workflow implementation
        uses: actions/checkout@v7.0.0
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .buildchain/workflow-shell
          persist-credentials: false
      - name: Execute oci-compose-preview-promote
        id: node
        uses: ./.buildchain/workflow-shell/actions/publication/oci-compose-preview-promote
        with:
          job-workflow-sha: ${{ toJSON(job.workflow_sha) }}
          secrets-buildchain-promotion-token: ${{ secrets.BUILDCHAIN_PROMOTION_TOKEN }}
