name: Release - Verify

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - publish-gate/major
      - major-gate

permissions:
  contents: read
  pull-requests: write

jobs:
  try:
    uses: ./.github/workflows/.release-verify.yml
    with:
      prebuild: false
      find-dependencies: false
      publish-versioning: false
      buildchain-repository: kungfu-systems/buildchain
  
  verify:
    # report status for branch protection rule
    needs: try
    runs-on: ubuntu-24.04
    steps:
      - name: report
        run: echo verified
